version: 2
sources:
  - name: congress_trades
    database: postgres
    schema: public
    tables:
      - name: politicians
      - name: stocks
      - name: house_trades
      - name: senate_trades
      